import textFieldModule = require("ui/text-field");
import label = require("ui/label");
import stack = require("ui/layouts/stack-layout");
import { Property } from "ui/core/view";
export declare class RichTextField extends stack.StackLayout {
    textField: textFieldModule.TextField;
    label: label.Label;
    fieldHeight: any;
    iconSize: any;
    fieldBorderWidth: any;
    fieldTopBorderWidth: any;
    fieldBottomBorderWidth: any;
    constructor();
    onLoad(eventData: any): void;
    static calculateLabelPadding(stackLayout: RichTextField): number;
}
export declare const secureProperty: Property<RichTextField, boolean>;
export declare const textPaddingLeftProperty: Property<RichTextField, string>;
export declare const fieldPaddingTopProperty: Property<RichTextField, string>;
export declare const iconColorProperty: Property<RichTextField, string>;
export declare const iconProperty: Property<RichTextField, string>;
export declare const iconSizeProperty: Property<RichTextField, number>;
export declare const fieldHeightProperty: Property<RichTextField, number>;
export declare const fieldColorProperty: Property<RichTextField, string>;
export declare const fieldPaddingLeftProperty: Property<RichTextField, string>;
export declare const fieldPaddingRightProperty: Property<RichTextField, string>;
export declare const fieldBackgroundColorProperty: Property<RichTextField, string>;
export declare const fieldHintProperty: Property<RichTextField, string>;
export declare const fieldHintColorProperty: Property<RichTextField, string>;
export declare const fieldBorderColorProperty: Property<RichTextField, string>;
export declare const fieldBorderWidthProperty: Property<RichTextField, number>;
export declare const fieldLeftBorderWidthProperty: Property<RichTextField, number>;
export declare const fieldRightBorderWidthProperty: Property<RichTextField, number>;
export declare const fieldTopBorderWidthProperty: Property<RichTextField, number>;
export declare const fieldBottomBorderWidthProperty: Property<RichTextField, number>;
